name: 'Changelog create release'
description: 'Creates a new release whenever CHANGELOG.md changes'
branding:
  color: 'blue'
  icon: file-text

inputs:
  github-token:
    description: 'GITHUB TOKEN'
    required: true
    default: ''
outputs:
  release-version:
    description: 'The updated release version'
runs:
  using: 'node20'
  main: 'dist/index.cjs'
