name: 'Changelog create release'
description: 'Creates a new release whenever CHANGELOG.md changes'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.cjs'
